### ISSUE TITLE
Bakgrund?

### ISSUE THREAD

**Issue by dpriskorn** [Alingsas-Kommun/PoorMansApi#2]
Hej, jag hittade hit via LinkedIn och jag har aldrig hört om Open E och vet lite om LDAP. Skulle ni kunna lägga till lite länkar eller bakgrund till READMEn?

Jag känner mig nyfiken på hur denna pusselbit passar in i era andra IT-lösningar. Vilket problem/behov löser den?

**Comment by Alingsaskommun** [comment]
Tack. Lägger till det du skrev + länkar.
